[project]
name = "ai-agents"
version = "0.1.0"
description = ""
authors = [
    {name = "laguagu",email = "AkuLeskinen@hotmail.com"}
]
readme = "README.md"
requires-python = ">=3.12.3,<4.0"
dependencies = [
    "langgraph>=0.0.36",
    "langchain-core>=0.1.0",
    "langchain-openai>=0.0.1",
    "typing-extensions>=4.5.0",
    "pydantic>=2.0.0",
    "python-dotenv>=1.0.0",
    "swarm @ git+https://github.com/openai/swarm.git"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false